name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # updates daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ManeeshaGee
          template: classic
          languages: yes
          activity: yes
          isocalendar: yes
